### ISSUE TITLE
The game crashed whilst initializing game Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'adaptivebrightness'! Exit-Code: -1

### ISSUE THREAD

**Issue by Cristelknight** [cominixo/AdaptiveBrightness#4]
[crash-2021-07-26_14.33.39-client.txt](https://github.com/cominixo/AdaptiveBrightness/files/6878175/crash-2021-07-26_14.33.39-client.txt)

**Comment by cominixo** [comment]
Ohh I must've missed that, you can install cloth config API to fix it but I'll include it next release

**Comment by cominixo** [comment]
Fixed on the latest commit, will release 1.0.2 soon
